version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drizzle-crash-course
    ports:
      - "5433:5432" # Maps local port 5433 to container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data

volumes:
  postgres_data:
